### ISSUE TITLE
pre/post CI jobs for pull requests.

### ISSUE THREAD

**Issue by stuij** [ARM-software/abi-aa#17]
As it says on the tin, we should have some CI in place for:

1. pre-commits: see if the documents are valid .rst, and see if there is any issue with generating pdfs.
2. post-commit job so we have pdfs of head, and for validation of the sanity of head.

**Comment by stuij** [comment]
At some point I had a github actions post-commit job running for this, but it turns out our arm repo is an old-style repo, and Github doesn't allow github actions on them :( So we should use something like Travis instead.

**Comment by fpetrogalli** [comment]
+1000 for Travis-CI, they even have Arm machines were we could run this :)

https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support

I think we should run the same set of script on all commits, on development branch/forks, for pre-merge control, and also the same sets of scripts for merges. Given we have opted for a rebase merge in #14  , we should  make sure that every single commits in the dev-branch/fork has a green flag.

In terms of what we need to test, I think we should run the following:

1. Check that RST syntax is valid, by using `rstcheck` (https://github.com/myint/rstcheck). It is quite good at finding major problems as broken link, unsupported syntax, and so on.
2. Check that all PDFs build by running the build script on all the specs. 

What we will have to do manually for each PR is:

1. Check that the rst renders correctly via github, by looking at its rendering in the dev branch / fork. Here we will have to trust the human being behind the operation, but I think it is not a big risk because rendering problems are quite easy to fix.
2. Check that the PDF renders correctly: can we have the PDFs produced and stored automatically somewhere for a pull request so that reviewers can click on it? I think we could deploy such artifacts on github pages, at least for rendering the latest version of master? https://docs.travis-ci.com/user/deployment/pages/ Not sure how well this would work for PRs.

Any other ideas?

**Comment by stuij** [comment]
I did some work today getting this to work with Travis. It wasn't hard at all, but saving artifacts isn't pretty. Yes you can deploy to Github pages, but that isn't very elegant as you're loosing the mapping between CI run and artifacts. Especially on pull requests.

However I looked again at Github Actions, and it turns out that it now works on legacy Github contracts as ours. So I updated/added the Github actions config I had from before: https://github.com/ARM-software/abi-aa/pull/56

It works really nice. We build on pull requests and push, with artifacts attached to the run. I think this includes builds after pull requests are merged. Artifacts are saved up till 90 days, which is plenty fine. I'm pretty happy with this solution.

**Comment by stuij** [comment]
merged https://github.com/ARM-software/abi-aa/pull/56. Closing this ticket.
